"""
Regression tests that lock the analysis pipeline against fixed reference
outputs stored under :mod:`tests/fixtures/`.

The fixtures are generated by :mod:`tests.build_fixtures` immediately after
Phase A; every subsequent change (Phase B JIT kernels, Phase C algorithmic
swaps) must reproduce these arrays within the documented tolerance.

Tolerance policy follows OPTIMIZATION.md §7:

* **Integer / categorical** outputs (flow direction, stream mask, viewshed,
  Strahler order): ``np.array_equal`` exact match.
* **Priority-flood filled DEM**: bit-identical — algorithm is deterministic.
* **Other float outputs**: max-RMS = 1e-5 (covers the float32 horizon
  dtype change in A.6 with room to spare for IEEE-754 reorderings).

Run with ``pytest tests/test_regression.py``.
"""
from __future__ import annotations
from pathlib import Path

import numpy as np
import pytest

from tests.synth_dem import NODATA, make_dem, make_dem_with_void


SIZE = 512
CELL_SIZE = 30.0
FIXTURE_DIR = Path(__file__).resolve().parent / "fixtures"
FIXTURES_PRESENT = (FIXTURE_DIR / f"dem_{SIZE}.npy").exists()


pytestmark = pytest.mark.skipif(
    not FIXTURES_PRESENT,
    reason=f"fixtures missing — run `python -m tests.build_fixtures --size {SIZE}` first",
)


def _load(name: str) -> np.ndarray:
    return np.load(FIXTURE_DIR / f"{name}.npy")


def _assert_close(actual: np.ndarray, expected: np.ndarray, rms_tol: float = 1e-5) -> None:
    assert actual.shape == expected.shape
    assert actual.dtype == expected.dtype
    diff = actual.astype(np.float64) - expected.astype(np.float64)
    # NaN positions must match; everywhere else the RMS must be tiny.
    a_nan = ~np.isfinite(actual)
    e_nan = ~np.isfinite(expected)
    assert np.array_equal(a_nan, e_nan), (
        f"NaN mask differs: {int(np.sum(a_nan ^ e_nan))} mismatched cells"
    )
    finite = ~a_nan
    if finite.any():
        rms = float(np.sqrt(np.mean(diff[finite] ** 2)))
        assert rms <= rms_tol, f"RMS {rms:.3e} exceeds tolerance {rms_tol:.0e}"


def _assert_exact(actual: np.ndarray, expected: np.ndarray) -> None:
    assert actual.shape == expected.shape
    assert actual.dtype == expected.dtype
    assert np.array_equal(actual, expected), "outputs differ from locked fixture"


# ── inputs are themselves locked, so regenerating them must be deterministic ──

def test_synth_dem_is_deterministic() -> None:
    _assert_exact(make_dem(SIZE), _load(f"dem_{SIZE}"))
    _assert_exact(make_dem_with_void(SIZE), _load(f"dem_void_{SIZE}"))


# ── primary derivatives ───────────────────────────────────────────────

@pytest.fixture(scope="module")
def dem() -> np.ndarray:
    return make_dem(SIZE)


@pytest.fixture(scope="module")
def dem_void() -> np.ndarray:
    return make_dem_with_void(SIZE)


def test_hillshade(dem: np.ndarray) -> None:
    from app.core.derivatives.hillshade import hillshade
    _assert_close(hillshade(dem, CELL_SIZE), _load(f"hillshade_{SIZE}"))


def test_hillshade_void(dem_void: np.ndarray) -> None:
    from app.core.derivatives.hillshade import hillshade
    _assert_close(hillshade(dem_void, CELL_SIZE, nodata=NODATA),
                  _load(f"hillshade_void_{SIZE}"))


def test_slope(dem: np.ndarray) -> None:
    from app.core.derivatives.slope import slope
    _assert_close(slope(dem, CELL_SIZE), _load(f"slope_{SIZE}"))


def test_slope_void(dem_void: np.ndarray) -> None:
    from app.core.derivatives.slope import slope
    _assert_close(slope(dem_void, CELL_SIZE, nodata=NODATA),
                  _load(f"slope_void_{SIZE}"))


def test_aspect(dem: np.ndarray) -> None:
    from app.core.derivatives.aspect import aspect
    _assert_close(aspect(dem, CELL_SIZE), _load(f"aspect_{SIZE}"))


@pytest.mark.parametrize("name,fn_name", [
    ("profile_curv", "profile_curvature"),
    ("plan_curv", "plan_curvature"),
    ("mean_curv", "mean_curvature"),
])
def test_curvature(dem: np.ndarray, name: str, fn_name: str) -> None:
    import app.core.derivatives.curvature as cv
    fn = getattr(cv, fn_name)
    _assert_close(fn(dem, CELL_SIZE), _load(f"{name}_{SIZE}"))


# ── indices ────────────────────────────────────────────────────────────

def test_tri(dem: np.ndarray) -> None:
    from app.core.indices.tri import tri
    _assert_close(tri(dem), _load(f"tri_{SIZE}"))


@pytest.mark.parametrize("fn_name,fixture", [
    ("roughness_range", "roughness_range"),
    ("roughness_sd", "roughness_sd"),
])
def test_roughness_simple(dem: np.ndarray, fn_name: str, fixture: str) -> None:
    import app.core.indices.roughness as r
    fn = getattr(r, fn_name)
    _assert_close(fn(dem), _load(f"{fixture}_{SIZE}"))


def test_vrm(dem: np.ndarray) -> None:
    from app.core.indices.roughness import vrm
    _assert_close(vrm(dem, CELL_SIZE), _load(f"vrm_{SIZE}"))


def test_sar(dem: np.ndarray) -> None:
    from app.core.indices.roughness import surface_area_ratio
    _assert_close(surface_area_ratio(dem, CELL_SIZE), _load(f"sar_{SIZE}"))


# ── visibility ────────────────────────────────────────────────────────

def test_multidirectional(dem: np.ndarray) -> None:
    from app.core.visibility.multidirectional import multidirectional_hillshade
    _assert_close(multidirectional_hillshade(dem, CELL_SIZE),
                  _load(f"multidir_{SIZE}"))


def test_sky_view_factor(dem: np.ndarray) -> None:
    from app.core.visibility.svf import sky_view_factor
    _assert_close(
        sky_view_factor(dem, CELL_SIZE, n_directions=8, max_radius=20),
        _load(f"svf_{SIZE}"),
    )


def test_positive_openness(dem: np.ndarray) -> None:
    from app.core.visibility.svf import positive_openness
    _assert_close(
        positive_openness(dem, CELL_SIZE, n_directions=8, max_radius=20),
        _load(f"pos_open_{SIZE}"),
    )


def test_negative_openness(dem: np.ndarray) -> None:
    from app.core.visibility.svf import negative_openness
    _assert_close(
        negative_openness(dem, CELL_SIZE, n_directions=8, max_radius=20),
        _load(f"neg_open_{SIZE}"),
    )


# ── hydrology (the Phase B JIT targets) ───────────────────────────────

@pytest.fixture(scope="module")
def filled() -> np.ndarray:
    from app.core.hydrology.fill_sinks import priority_flood
    return priority_flood(make_dem(SIZE))


def test_priority_flood(dem: np.ndarray) -> None:
    """Bit-identical — algorithm is deterministic, no reordering allowed."""
    from app.core.hydrology.fill_sinks import priority_flood
    _assert_exact(priority_flood(dem), _load(f"priority_flood_{SIZE}"))


def test_breach_and_fill(dem: np.ndarray) -> None:
    """Bit-identical — breach order is deterministic given the input."""
    from app.core.hydrology.fill_sinks import breach_and_fill
    _assert_exact(breach_and_fill(dem), _load(f"breach_fill_{SIZE}"))


def test_d8_flow_direction(filled: np.ndarray) -> None:
    from app.core.hydrology.flow_direction import d8_flow_direction
    _assert_exact(d8_flow_direction(filled, CELL_SIZE),
                  _load(f"d8_flow_dir_{SIZE}"))


def test_d8_flow_accumulation(filled: np.ndarray) -> None:
    from app.core.hydrology.flow_direction import d8_flow_direction
    from app.core.hydrology.flow_accumulation import d8_flow_accumulation
    fd = d8_flow_direction(filled, CELL_SIZE)
    _assert_close(d8_flow_accumulation(filled, fd),
                  _load(f"d8_flow_accum_{SIZE}"))


def test_d_infinity_pipeline(filled: np.ndarray) -> None:
    from app.core.hydrology.flow_direction import d_infinity_flow_direction
    from app.core.hydrology.flow_accumulation import d_inf_flow_accumulation
    angle, _ = d_infinity_flow_direction(filled, CELL_SIZE)
    _assert_close(angle, _load(f"d_inf_angle_{SIZE}"))
    _assert_close(d_inf_flow_accumulation(filled, angle),
                  _load(f"d_inf_flow_accum_{SIZE}"))


def test_streams_and_strahler(filled: np.ndarray) -> None:
    from app.core.hydrology.flow_direction import d8_flow_direction
    from app.core.hydrology.flow_accumulation import d8_flow_accumulation
    from app.core.hydrology.streams import extract_streams, strahler_order
    fd = d8_flow_direction(filled, CELL_SIZE)
    fa = d8_flow_accumulation(filled, fd)
    streams = extract_streams(fa, threshold=float(np.nanpercentile(fa, 99)))
    _assert_exact(streams, _load(f"streams_{SIZE}"))
    _assert_exact(strahler_order(streams, fd), _load(f"strahler_{SIZE}"))


def test_viewshed(filled: np.ndarray) -> None:
    from app.core.visibility.viewshed import viewshed
    out = viewshed(filled, CELL_SIZE, SIZE // 2, SIZE // 2,
                   observer_height=10.0, max_radius=SIZE // 4)
    _assert_exact(out, _load(f"viewshed_{SIZE}"))
